export const serif = "'Spectral', Georgia, serif";
export const sans = "'Inter', -apple-system, sans-serif";
export const mono = "'IBM Plex Mono', ui-monospace, monospace";

export const styles = {
  page: {
    minHeight: "100vh",
    background: "#f5f1e6",
    color: "#17190f",
    fontFamily: sans,
    display: "flex",
    flexDirection: "column",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "22px 28px",
    borderBottom: "1px solid #ddd6c2",
  },
  subNav: {
    display: "flex",
    gap: "8px",
    padding: "14px 28px 0",
  },
  subNavLink: {
    fontFamily: mono,
    fontSize: "11px",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "#6f7460",
    textDecoration: "none",
    border: "1px solid #ddd6c2",
    borderRadius: "20px",
    padding: "6px 14px",
  },
  subNavLinkActive: {
    color: "#fdfbf3",
    background: "#a4275a",
    border: "1px solid #a4275a",
  },
  logo: {
    fontFamily: serif,
    fontWeight: 500,
    fontStyle: "italic",
    fontSize: "19px",
    letterSpacing: "0.02em",
    color: "#17190f",
    background: "transparent",
    border: "none",
    padding: 0,
    cursor: "pointer",
    textDecoration: "none",
  },
  nav: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: "18px",
  },
  navLink: {
    background: "transparent",
    border: "none",
    padding: 0,
    color: "#5c6050",
    fontFamily: sans,
    fontSize: "12.5px",
    fontWeight: 500,
    letterSpacing: "0.04em",
    cursor: "pointer",
    textDecoration: "none",
  },
  navLinkActive: {
    color: "#17190f",
    borderBottom: "2px solid #a4275a",
    paddingBottom: "3px",
  },
  addBtnRow: {
    display: "flex",
    justifyContent: "center",
    padding: "8px 28px 56px",
  },
  addBtn: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    gap: "7px",
    background: "#a4275a",
    color: "#fdfbf3",
    border: "1px solid #a4275a",
    borderRadius: "3px",
    padding: "8px 14px",
    fontFamily: sans,
    fontSize: "12.5px",
    fontWeight: 500,
    letterSpacing: "0.03em",
    cursor: "pointer",
  },
  hiddenFileInput: {
    position: "absolute",
    width: "1px",
    height: "1px",
    padding: 0,
    margin: "-1px",
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    border: 0,
  },
  carouselWrap: {
    position: "relative",
    width: "100%",
    height: "min(64vh, 620px)",
    minHeight: "340px",
    background: "#e9e2cf",
    outline: "none",
  },
  emptyState: {
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "12px",
  },
  emptyText: {
    fontFamily: sans,
    fontSize: "13px",
    color: "#83876f",
    letterSpacing: "0.02em",
    textAlign: "center",
    padding: "0 20px",
  },
  imageStage: {
    position: "relative",
    width: "100%",
    height: "100%",
  },
  image: {
    width: "100%",
    height: "100%",
    objectFit: "contain",
    display: "block",
    filter: "saturate(1.05) contrast(1.05)",
  },
  vignette: {
    position: "absolute",
    inset: 0,
    background:
      "linear-gradient(180deg, rgba(10,8,6,0.30) 0%, rgba(10,8,6,0) 24%, rgba(10,8,6,0) 60%, rgba(10,8,6,0.6) 100%), radial-gradient(ellipse at center, rgba(0,0,0,0) 55%, rgba(8,6,5,0.3) 100%)",
    pointerEvents: "none",
  },
  dateRail: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: "36px",
    background: "rgba(15,12,9,0.6)",
    borderRight: "1px solid rgba(253,251,243,0.18)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  dateRailText: {
    writingMode: "vertical-rl",
    transform: "rotate(180deg)",
    fontFamily: mono,
    fontSize: "11px",
    letterSpacing: "0.12em",
    color: "#fdfbf3",
  },
  caption: {
    position: "absolute",
    left: "52px",
    bottom: "22px",
    display: "flex",
    flexDirection: "column",
    gap: "3px",
  },
  captionTitle: {
    fontFamily: serif,
    fontStyle: "italic",
    fontWeight: 500,
    fontSize: "21px",
    color: "#fdfbf3",
  },
  captionCount: {
    fontFamily: mono,
    fontSize: "10.5px",
    color: "#e4dfcc",
    letterSpacing: "0.08em",
  },
  deleteCurrent: {
    position: "absolute",
    right: "18px",
    bottom: "22px",
    background: "rgba(15,12,9,0.55)",
    border: "1px solid rgba(253,251,243,0.2)",
    borderRadius: "3px",
    padding: "8px",
    color: "#fdfbf3",
    cursor: "pointer",
    display: "flex",
  },
  navBtn: {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    background: "rgba(15,12,9,0.5)",
    border: "1px solid rgba(253,251,243,0.2)",
    borderRadius: "3px",
    padding: "8px",
    color: "#fdfbf3",
    cursor: "pointer",
    display: "flex",
  },
  archive: {
    padding: "26px 28px 48px",
  },
  archiveHeader: {
    fontFamily: mono,
    fontSize: "10.5px",
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: "#83876f",
    marginBottom: "14px",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(120px, 1fr))",
    gap: "12px",
  },
  thumbWrap: {
    background: "transparent",
    border: "1px solid transparent",
    borderRadius: "2px",
    padding: "3px",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    textAlign: "left",
  },
  thumbImg: {
    width: "100%",
    aspectRatio: "4 / 3",
    objectFit: "cover",
    display: "block",
    filter: "saturate(1.02)",
  },
  thumbDate: {
    fontFamily: mono,
    fontSize: "10px",
    color: "#6f7460",
    letterSpacing: "0.04em",
    paddingLeft: "2px",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(15,12,9,0.55)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "20px",
    zIndex: 50,
  },
  modal: {
    background: "#ffffff",
    border: "1px solid #ddd6c2",
    borderRadius: "4px",
    padding: "22px",
    width: "min(420px, 100%)",
    display: "flex",
    flexDirection: "column",
    gap: "14px",
    maxHeight: "90vh",
    overflowY: "auto",
    boxShadow: "0 18px 40px rgba(23,25,15,0.18)",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modalTitle: {
    fontFamily: serif,
    fontStyle: "italic",
    fontWeight: 500,
    fontSize: "18px",
    color: "#17190f",
  },
  modalPreview: {
    width: "100%",
    maxHeight: "220px",
    objectFit: "cover",
    borderRadius: "2px",
    border: "1px solid #ddd6c2",
  },
  label: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    fontFamily: mono,
    fontSize: "10.5px",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "#6f7460",
  },
  input: {
    background: "#fbf9f2",
    border: "1px solid #ddd6c2",
    borderRadius: "3px",
    padding: "9px 10px",
    color: "#17190f",
    fontFamily: sans,
    fontSize: "13.5px",
    textTransform: "none",
    letterSpacing: "normal",
  },
  modalActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "10px",
    marginTop: "4px",
  },
  primaryBtn: {
    background: "#a4275a",
    border: "1px solid #7e1a44",
    color: "#fdfbf3",
    borderRadius: "3px",
    padding: "9px 16px",
    fontFamily: sans,
    fontSize: "12.5px",
    fontWeight: 500,
    cursor: "pointer",
  },
  secondaryBtn: {
    background: "transparent",
    border: "1px solid #ddd6c2",
    color: "#4a4d3f",
    borderRadius: "3px",
    padding: "9px 16px",
    fontFamily: sans,
    fontSize: "12.5px",
    cursor: "pointer",
  },
  dangerBtn: {
    background: "#b5303a",
    border: "1px solid #7e1620",
    color: "#fdf3f0",
    borderRadius: "3px",
    padding: "9px 16px",
    fontFamily: sans,
    fontSize: "12.5px",
    fontWeight: 500,
    cursor: "pointer",
  },
  confirmModal: {
    background: "#ffffff",
    border: "1px solid #ddd6c2",
    borderRadius: "4px",
    padding: "22px",
    width: "min(340px, 100%)",
    boxShadow: "0 18px 40px rgba(23,25,15,0.18)",
  },
  confirmText: {
    fontFamily: sans,
    fontSize: "13.5px",
    color: "#17190f",
    margin: "0 0 16px",
  },
  errorToast: {
    position: "fixed",
    bottom: "20px",
    left: "50%",
    transform: "translateX(-50%)",
    background: "#b5303a",
    border: "1px solid #7e1620",
    color: "#fdf3f0",
    padding: "10px 16px",
    borderRadius: "4px",
    fontSize: "12.5px",
    fontFamily: sans,
    zIndex: 100,
  },
  textPage: {
    padding: "64px 28px",
    maxWidth: "620px",
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
    gap: "14px",
    flex: 1,
    width: "100%",
  },
  textEyebrow: {
    fontFamily: mono,
    fontSize: "10.5px",
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: "#a4275a",
  },
  textHeading: {
    fontFamily: serif,
    fontStyle: "italic",
    fontWeight: 500,
    fontSize: "33px",
    color: "#17190f",
    margin: "0 0 8px",
  },
  textBody: {
    fontFamily: sans,
    fontSize: "14.5px",
    lineHeight: 1.7,
    color: "#3d4033",
    margin: 0,
  },
  textNote: {
    fontFamily: mono,
    fontSize: "11px",
    color: "#8a8e78",
    marginTop: "8px",
  },
  contactBlock: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    marginTop: "6px",
  },
  contactLine: {
    fontFamily: sans,
    fontSize: "15.5px",
    color: "#17190f",
  },
  contactLink: {
    fontFamily: mono,
    fontSize: "13.5px",
    color: "#a4275a",
    marginTop: "6px",
    textDecoration: "none",
    borderBottom: "1px solid #a4275a",
    width: "fit-content",
  },
  passwordGate: {
    display: "flex",
    gap: "8px",
    alignItems: "center",
  },
};
